server:
  port: 8088
spring:
  application:
    name: tc-user-service
  profiles:
    include: common

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# JWT配置
jwt:
  secret: tc-user-service-jwt-secret-key-for-distributed-system-2024
  expiration: 3600